#!/usr/bin/env bash


# +-------------+
# | Terraform   |
# +-------------+

alias tf='terraform'


# +--------+
# | Grep   |
# +--------+

alias fg='grep --color=always -ri '

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

# +----+
# | ls |
# +----+

alias ls='ls -l --color=auto'
alias ll='ls -lahFtr --color=auto'
alias l='ls --color=auto'


# +------+
# | dust |
# +------+

alias dust='du -sh * | sort -hr'

# +-----+
# | bat |
# +-----+

alias batl='bat --paging=never -l log'

# +--------+
# | Neovim |
# +--------+

alias vim='nvim'
alias vi='nvim'
alias nvimfr='nvim +e /tmp/scratchpad.md -c "set spelllang=fr"'

# +-----+
# | Git |
# +-----+

alias gs='git status'
alias gl='git log --oneline'
alias glol='git log --graph --abbrev-commit --oneline --decorate'
alias gvim='git log --graph --abbrev-commit --oneline --decorate | vim'
alias vidiff='git diff | vim'

# Folders
alias int='cd $HOME/projects/greenway/iac/intergy'
alias ps='cd $HOME/projects/greenway/iac/primesuite'
alias md='cd $HOME/projects/greenway/iac/mediadent'
alias mm='cd $HOME/projects/greenway/iac/medman'
alias auth='cd $HOME/projects/greenway/iac/authoring'
alias ds='cd $HOME/projects/greenway/iac/dirserv'
alias root='cd $HOME/projects/'
alias gw='cd $HOME/projects/greenway'
alias poc='cd $HOME/projects/poc'

alias mv='mv -v'

alias todo='(cd $HOME/projects && ff todo.md) | xargs nvim'
